### ISSUE TITLE
jar包构建失败

### ISSUE THREAD

**Issue by Matsuzaka2** [Magic-Emerge/magic-emerge#2]
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/2f9f8eb5-ce5c-4e7e-800c-fbb067718036)
构建jar包时候出错,maven3.9.6 java8 Intelij IDEA

**Comment by GZ315200** [comment]
在后端项目根目录下执行，`mvn install -DskipTests` , maven版本3.9以上, jdk版本1.8以上

**Comment by Matsuzaka2** [comment]
> 在室内项目根目录下执行，mvn clean install --Dmaven.skip.test=true

跳过了测试后确实能完成构建,但出来的包放上docker compose up就会报错

**Comment by GZ315200** [comment]
> > 在室内项目根目录下执行，mvn clean install --Dmaven.skip.test=true
> 
> 跳过了测试后确实能完成构建,但出来的包放上docker compose up就会报错

如果报错的话，可以将web文件下Dockerfile文件的第九行换成`RUN  npm install --registry=http://registry.npmmirror.com`
