### ISSUE TITLE
docker-compose运行时遇到错误

### ISSUE THREAD

**Issue by Matsuzaka2** [Magic-Emerge/magic-emerge#3]
如图,npm ci运行不了
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/206a629d-5668-4993-b418-48efebc1ed11)
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/9f9677ba-d60c-483f-bcdc-0476dd4d76a4)不然就是
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/6be5d68a-3b46-4a59-a6dd-f6553382554a)
 一直卡在这

**Comment by Matsuzaka2** [comment]
阿里云的linux

**Comment by Matsuzaka2** [comment]
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/4012fd23-6dd6-4b8d-a3ca-1a2b4b4c3baf)
 用本机npm运行npm ci如下 有什么头绪吗

**Comment by GZ315200** [comment]
不好意思，因为我用GCP，所以国内的话需要在这里设置一下的国内的源，在web下的docker文件里里加入就行

**Comment by Matsuzaka2** [comment]
> 不好意思，因为我用GCP，所以国内的话需要在这里设置一下的国内的源，在web下的docker文件里里加入就行

你好,方便说下怎么设置吗
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/b4ed183b-b107-4e77-a87e-cf618e934cb7)
这是我的web目录
