### ISSUE TITLE
Docker compose运行时出现问题

### ISSUE THREAD

**Issue by Matsuzaka2** [Magic-Emerge/magic-emerge#4]
![image](https://github.com/Magic-Emerge/magic-emerge/assets/100253928/be2fe4f7-b352-4078-8a79-f6d4b0a8265f)
如图,npm ci时出现错误,

**Comment by GZ315200** [comment]
> ![image](https://private-user-images.githubusercontent.com/100253928/299908672-be2fe4f7-b352-4078-8a79-f6d4b0a8265f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTU0NzMsIm5iZiI6MTcwNjc5NTE3MywicGF0aCI6Ii8xMDAyNTM5MjgvMjk5OTA4NjcyLWJlMmZlNGY3LWIzNTItNDA3OC04YTc5LWY2ZDRiMGE4MjY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMzQ2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGJiMTVjZDgzY2JjNGEyOWMxMDY4ZmQ4OGY2MjU3MTZhZjc3ZGFjN2ViZmU5M2E0NjEwY2VlNzJhZWNiMWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vF6duNEb7sYQ9n_a6uga0RXFhHofz4RIiUYjfHDwth0) 如图,npm ci时出现错误,

#2
